### ISSUE TITLE
Fallo en Heroku

### ISSUE THREAD

**Issue by AdCalzadilla** [ULL-ESIT-GRADOII-PL/proyecto-adrian_adexe#2]
A veces no funciona el _parser_ en **heroku**. Al recargar la página funciona correctamente.

**Comment by crguezl** [comment]
Ahora mismo esta funcionando @AdCalzadilla, @alu0100769609.
👍 
Buen trabajo

**Comment by AdCalzadilla** [comment]
Solucionado definitivamente. Era un problema con el **localStorage**.
